### ISSUE TITLE
$ python WillSpaceFiller.py Traceback (most recent call last):   File "WillSpaceFiller.py", line 3, in <module>     total, used, free = shutil.disk_usage(__file__) AttributeError: 'module' object has no attribute 'disk_usage'

### ISSUE THREAD

**Issue by williammac2004** [williammac2004/SpaceFiller#2]
$ python WillSpaceFiller.py
Traceback (most recent call last):
  File "WillSpaceFiller.py", line 3, in <module>
    total, used, free = shutil.disk_usage(__file__)
AttributeError: 'module' object has no attribute 'disk_usage'

**Comment by williammac2004** [comment]
The reas
